### ISSUE TITLE
Продукты имеют одинаковые поля и дублируют друг друга

### ISSUE THREAD

**Issue by alexeychernykh** [yaroslav-hub/Shop#1]
https://github.com/yaroslav-hub/Shop/blob/63403b56a817219ee1e6824bb0433e49bd4654d1/ShopLib/BreadItem.cs#L11

Поля у продуктов одинаковые, отдилчаются только значение. Лучше передать эти значения в конструкторе при инициализации объектов. Сейчас нет необходимости в разных классах продуктов, т.к. их структура идентична

**Comment by yaroslav-hub** [comment]
Добавил класс DefineItem с одноимённым методом для объявления продуктов. Метод принимает три параметра: название продукта, категорию и цену. Все ненужные индивидуальные для каждого продукта классы убрал.

[Коммит с исправлением](https://github.com/yaroslav-hub/Shop/commit/415337a3c50775c21d448ea67aa3e93af7ef906f)
