### ISSUE TITLE
Использовать более удачну структуру для передачи параметров

### ISSUE THREAD

**Issue by alexeychernykh** [yaroslav-hub/Shop#2]
https://github.com/yaroslav-hub/Shop/blob/63403b56a817219ee1e6824bb0433e49bd4654d1/Shop/Program.cs#L32

Тут лучше использовать массив названий.

**Comment by yaroslav-hub** [comment]
Изначально предполагалось, что список продуктов будет вводиться пользователем, поэтому в качестве тестовых данных сразу передавал строку в метод. Исправил это на пользовательский ввод.

[Коммит с исправлением](https://github.com/yaroslav-hub/Shop/commit/969e3a5b08e5216fe27d633cf0b81eea7a4fb950)

**Comment by alexeychernykh** [comment]
Имелось в виду лучше в Calculate передать массив string[] или List<string>
А парсинг оставить прямо в Program.cs

**Comment by yaroslav-hub** [comment]
Теперь понял.

[Коммит с исправлением](https://github.com/yaroslav-hub/Shop/commit/1eb7e5d9b5f3771eb372f051328bdac7e82f0f92)
